-- Flashi 0015: hardening for FSRS retries, semantic workers, media integrity
-- and user-scoped incremental synchronization.
--
-- This migration keeps the existing 0014 function signatures compatible while
-- adding an idempotent review entry point for offline clients and workers.

-- ---------------------------------------------------------------------------
-- Integrity metadata and idempotency keys.
-- ---------------------------------------------------------------------------
alter table public.notes
  add column if not exists embedding_content_hash text;

alter table public.card_media
  add column if not exists sha256_hash text;

alter table public.review_logs
  add column if not exists client_review_id uuid;

DO $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'notes_embedding_content_hash_check'
      and conrelid = 'public.notes'::regclass
  ) then
    alter table public.notes add constraint notes_embedding_content_hash_check
      check (
        embedding_content_hash is null
        or embedding_content_hash ~ '^[0-9a-fA-F]{64}$'
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'card_media_sha256_hash_check'
      and conrelid = 'public.card_media'::regclass
  ) then
    alter table public.card_media add constraint card_media_sha256_hash_check
      check (sha256_hash is null or sha256_hash ~ '^[0-9a-fA-F]{64}$');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'card_media_storage_path_owner_check'
      and conrelid = 'public.card_media'::regclass
  ) then
    alter table public.card_media add constraint card_media_storage_path_owner_check
      check (storage_path like user_id::text || '/%');
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'review_logs_time_spent_nonnegative_check'
      and conrelid = 'public.review_logs'::regclass
  ) then
    alter table public.review_logs add constraint review_logs_time_spent_nonnegative_check
      check (time_spent_ms is null or time_spent_ms >= 0);
  end if;
end $$;

create unique index if not exists review_logs_user_client_review_id
  on public.review_logs (user_id, client_review_id)
  where client_review_id is not null;

create index if not exists idx_review_logs_user_algorithm_date
  on public.review_logs (user_id, algorithm, reviewed_at asc);

create index if not exists idx_card_media_user_sha256
  on public.card_media (user_id, sha256_hash)
  where sha256_hash is not null;

create index if not exists idx_learning_state_state_due
  on public.card_learning_state (user_id, state, due_at)
  where is_suspended = false;

create index if not exists idx_cards_user_deck_active
  on public.cards (user_id, deck_id, id)
  where deleted_at is null;

-- ---------------------------------------------------------------------------
-- Idempotent FSRS persistence.
-- The client_review_id is generated by the client and reused on retries. The
-- server remains the authority for user_id, reviewed_at and USN.
-- ---------------------------------------------------------------------------
create or replace function public.record_review_fsrs6_idempotent(
  p_card_id uuid,
  p_rating public.review_rating,
  p_time_spent_ms integer,
  p_new_state public.card_state,
  p_new_interval_days numeric,
  p_new_due_at timestamptz,
  p_fsrs_state smallint,
  p_fsrs_step integer,
  p_fsrs_retrievability numeric,
  p_elapsed_days integer,
  p_scheduled_days integer,
  p_new_stability numeric,
  p_new_difficulty numeric,
  p_parameter_version integer,
  p_algorithm_state jsonb,
  p_device_id text,
  p_session_id uuid,
  p_client_review_id uuid,
  p_expected_usn bigint default null
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_prev public.card_learning_state%rowtype;
  v_user_id uuid := auth.uid();
  v_review_id uuid;
  v_existing_review_id uuid;
  v_existing_card_id uuid;
begin
  if v_user_id is null then
    raise exception 'Authentication is required';
  end if;

  if p_client_review_id is not null then
    select id, card_id into v_existing_review_id, v_existing_card_id
    from public.review_logs
    where user_id = v_user_id
      and client_review_id = p_client_review_id;

    if v_existing_review_id is not null then
      if v_existing_card_id <> p_card_id then
        raise exception 'client_review_id is already associated with another card';
      end if;
      return v_existing_review_id;
    end if;
  end if;

  if p_time_spent_ms is not null and p_time_spent_ms < 0 then
    raise exception 'p_time_spent_ms cannot be negative';
  end if;
  if p_new_interval_days is null or p_new_interval_days < 0 then
    raise exception 'p_new_interval_days must be non-negative';
  end if;
  if p_new_due_at is null then
    raise exception 'p_new_due_at is required';
  end if;
  if p_fsrs_state is null or p_fsrs_state not between 0 and 3 then
    raise exception 'p_fsrs_state must be between 0 and 3';
  end if;
  if p_fsrs_step is not null and p_fsrs_step < 0 then
    raise exception 'p_fsrs_step cannot be negative';
  end if;
  if p_fsrs_retrievability is not null
     and (p_fsrs_retrievability < 0 or p_fsrs_retrievability > 1) then
    raise exception 'p_fsrs_retrievability must be between 0 and 1';
  end if;
  if p_new_stability is not null and p_new_stability <= 0 then
    raise exception 'p_new_stability must be positive';
  end if;
  if p_new_difficulty is not null
     and (p_new_difficulty < 1 or p_new_difficulty > 10) then
    raise exception 'p_new_difficulty must be between 1 and 10';
  end if;

  select * into v_prev
  from public.card_learning_state
  where user_id = v_user_id and card_id = p_card_id
  for update;

  if not found then
    raise exception 'No learning state for card % / current user', p_card_id;
  end if;

  if p_expected_usn is not null and v_prev.usn <> p_expected_usn then
    raise exception 'CARD_STATE_CHANGED';
  end if;

  -- The row lock closes the race between the initial duplicate lookup and a
  -- concurrent review of the same card. The unique index handles the final
  -- race between two requests with the same client_review_id.
  if p_client_review_id is not null then
    select id, card_id into v_existing_review_id, v_existing_card_id
    from public.review_logs
    where user_id = v_user_id
      and client_review_id = p_client_review_id;

    if v_existing_review_id is not null then
      if v_existing_card_id <> p_card_id then
        raise exception 'client_review_id is already associated with another card';
      end if;
      return v_existing_review_id;
    end if;
  end if;

  insert into public.review_logs (
    user_id, card_id, rating, time_spent_ms,
    prev_state, new_state, prev_interval_days, new_interval_days,
    prev_due_at, new_due_at, prev_ease_factor, new_ease_factor,
    prev_stability, new_stability, prev_difficulty, new_difficulty,
    algorithm, device_id, session_id, fsrs_version, elapsed_days,
    scheduled_days, fsrs_retrievability, fsrs_parameter_version,
    client_review_id
  ) values (
    v_user_id, p_card_id, p_rating, p_time_spent_ms,
    v_prev.state, p_new_state, v_prev.interval_days, p_new_interval_days,
    v_prev.due_at, p_new_due_at, v_prev.ease_factor, v_prev.ease_factor,
    v_prev.stability, p_new_stability, v_prev.difficulty, p_new_difficulty,
    'fsrs', p_device_id, p_session_id, 'fsrs-6', p_elapsed_days,
    p_scheduled_days, p_fsrs_retrievability, coalesce(p_parameter_version, 1),
    p_client_review_id
  )
  on conflict (user_id, client_review_id)
  where client_review_id is not null
  do nothing
  returning id into v_review_id;

  if v_review_id is null then
    select id, card_id into v_review_id, v_existing_card_id
    from public.review_logs
    where user_id = v_user_id
      and client_review_id = p_client_review_id;
    if v_existing_card_id <> p_card_id then
      raise exception 'client_review_id is already associated with another card';
    end if;
    return v_review_id;
  end if;

  update public.card_learning_state set
    state = p_new_state,
    due_at = p_new_due_at,
    interval_days = p_new_interval_days,
    stability = p_new_stability,
    difficulty = p_new_difficulty,
    fsrs_version = 'fsrs-6',
    fsrs_state = p_fsrs_state,
    fsrs_step = p_fsrs_step,
    fsrs_retrievability = p_fsrs_retrievability,
    fsrs_last_scheduled_at = now(),
    algorithm = 'fsrs',
    algorithm_state = coalesce(p_algorithm_state, '{}'::jsonb),
    reps = reps + 1,
    lapses = lapses + case when p_rating = 'again' then 1 else 0 end,
    last_reviewed_at = now()
  where user_id = v_user_id and card_id = p_card_id;

  insert into public.daily_statistics (
    user_id, stat_date, cards_studied, new_cards_studied,
    reviews_count, correct_count, incorrect_count, time_studied_ms
  ) values (
    v_user_id, current_date, 1,
    case when v_prev.state = 'new' then 1 else 0 end,
    1,
    case when p_rating in ('good', 'easy') then 1 else 0 end,
    case when p_rating in ('again', 'hard') then 1 else 0 end,
    coalesce(p_time_spent_ms, 0)
  )
  on conflict (user_id, stat_date) do update set
    cards_studied = public.daily_statistics.cards_studied + 1,
    new_cards_studied = public.daily_statistics.new_cards_studied +
      case when v_prev.state = 'new' then 1 else 0 end,
    reviews_count = public.daily_statistics.reviews_count + 1,
    correct_count = public.daily_statistics.correct_count +
      case when p_rating in ('good', 'easy') then 1 else 0 end,
    incorrect_count = public.daily_statistics.incorrect_count +
      case when p_rating in ('again', 'hard') then 1 else 0 end,
    time_studied_ms = public.daily_statistics.time_studied_ms + coalesce(p_time_spent_ms, 0),
    updated_at = now();

  return v_review_id;
end;
$$;

-- Preserve the 0014 API while routing it through the hardened transaction.
create or replace function public.record_review_fsrs6(
  p_card_id uuid,
  p_rating public.review_rating,
  p_time_spent_ms integer,
  p_new_state public.card_state,
  p_new_interval_days numeric,
  p_new_due_at timestamptz,
  p_fsrs_state smallint,
  p_fsrs_step integer,
  p_fsrs_retrievability numeric,
  p_elapsed_days integer,
  p_scheduled_days integer,
  p_new_stability numeric,
  p_new_difficulty numeric,
  p_parameter_version integer default 1,
  p_algorithm_state jsonb default '{}'::jsonb,
  p_device_id text default null,
  p_session_id uuid default null
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  perform public.record_review_fsrs6_idempotent(
    p_card_id,
    p_rating,
    p_time_spent_ms,
    p_new_state,
    p_new_interval_days,
    p_new_due_at,
    p_fsrs_state,
    p_fsrs_step,
    p_fsrs_retrievability,
    p_elapsed_days,
    p_scheduled_days,
    p_new_stability,
    p_new_difficulty,
    p_parameter_version,
    p_algorithm_state,
    p_device_id,
    p_session_id,
    null,
    null
  );
end;
$$;

comment on function public.record_review_fsrs6_idempotent(
  uuid, public.review_rating, integer, public.card_state, numeric,
  timestamptz, smallint, integer, numeric, integer, integer, numeric,
  numeric, integer, jsonb, text, uuid, uuid, bigint
) is
  'Atomic FSRS-6 review persistence with a per-user client idempotency key.';

-- ---------------------------------------------------------------------------
-- Safer sync query and maintenance helper.
-- The incremental cursor is global, but active content is restricted to rows
-- owned by the authenticated user. Shared/public content can be fetched by its
-- normal read policies and is not mixed into a private offline cursor.
-- ---------------------------------------------------------------------------
create or replace function public.get_incremental_sync(
  p_after_usn bigint default 0,
  p_limit integer default 500
)
returns table (
  entity_type text,
  entity_key text,
  usn bigint,
  is_deleted boolean,
  payload jsonb
)
language sql
security invoker
stable
set search_path = public
as $$
  with changes as (
    select 'deck'::text, d.id::text, d.usn, false, to_jsonb(d)
    from public.decks d
    where d.user_id = auth.uid() and d.deleted_at is null and d.usn > p_after_usn

    union all
    select 'note', n.id::text, n.usn, false, to_jsonb(n)
    from public.notes n
    where n.user_id = auth.uid() and n.deleted_at is null and n.usn > p_after_usn

    union all
    select 'card', c.id::text, c.usn, false, to_jsonb(c)
    from public.cards c
    where c.user_id = auth.uid() and c.deleted_at is null and c.usn > p_after_usn

    union all
    select 'card_media', m.id::text, m.usn, false, to_jsonb(m)
    from public.card_media m
    where m.user_id = auth.uid() and m.usn > p_after_usn

    union all
    select 'card_learning_state', s.id::text, s.usn, false, to_jsonb(s)
    from public.card_learning_state s
    where s.user_id = auth.uid() and s.usn > p_after_usn

    union all
    select 'review_log', r.id::text, r.usn, false, to_jsonb(r)
    from public.review_logs r
    where r.user_id = auth.uid() and r.usn > p_after_usn

    union all
    select 'tag', t.id::text, t.usn, false, to_jsonb(t)
    from public.tags t
    where t.user_id = auth.uid() and t.usn > p_after_usn

    union all
    select 'card_template', t.id::text, t.usn, false, to_jsonb(t)
    from public.card_templates t
    where t.user_id = auth.uid() and t.usn > p_after_usn

    union all
    select 'study_settings', s.user_id::text, s.usn, false, to_jsonb(s)
    from public.study_settings s
    where s.user_id = auth.uid() and s.usn > p_after_usn

    union all
    select 'user_deck_settings', s.user_id::text || ':' || s.deck_id::text,
           s.usn, false, to_jsonb(s)
    from public.user_deck_settings s
    where s.user_id = auth.uid() and s.usn > p_after_usn

    union all
    select 'daily_statistics', s.user_id::text || ':' || s.stat_date::text,
           s.usn, false, to_jsonb(s)
    from public.daily_statistics s
    where s.user_id = auth.uid() and s.usn > p_after_usn

    union all
    select 'note_card_definition', d.id::text, d.usn, false, to_jsonb(d)
    from public.note_card_definitions d
    where d.usn > p_after_usn

    union all
    select 'note_cloze_deletion', d.id::text, d.usn, false, to_jsonb(d)
    from public.note_cloze_deletions d
    where d.usn > p_after_usn

    union all
    select 'fsrs_optimization_run', o.id::text, o.usn, false, to_jsonb(o)
    from public.fsrs_optimization_runs o
    where o.user_id = auth.uid() and o.usn > p_after_usn

    union all
    select 'card_tag', ct.card_id::text || ':' || ct.tag_id::text,
           ct.usn, false, to_jsonb(ct)
    from public.card_tags ct
    join public.cards c on c.id = ct.card_id
    where c.user_id = auth.uid() and ct.usn > p_after_usn

    union all
    select g.entity_type, g.entity_key, g.usn, true,
           jsonb_build_object(
             'entity_type', g.entity_type,
             'entity_key', g.entity_key,
             'deleted_at', g.deleted_at
           )
    from public.graves g
    where g.user_id = auth.uid() and g.usn > p_after_usn
  )
  select *
  from changes
  order by usn asc
  limit least(greatest(coalesce(p_limit, 500), 1), 5000);
$$;

create or replace function public.list_orphaned_card_media(
  p_limit integer default 100
)
returns table (
  media_id uuid,
  storage_bucket text,
  storage_path text
)
language sql
security invoker
stable
set search_path = public
as $$
  select m.id, m.storage_bucket, m.storage_path
  from public.card_media m
  where m.user_id = auth.uid()
    and not exists (
      select 1
      from public.cards c
      where c.id = m.card_id and c.deleted_at is null
    )
  order by m.created_at asc
  limit least(greatest(coalesce(p_limit, 100), 1), 1000);
$$;

comment on function public.get_incremental_sync(bigint, integer) is
  'Returns owned active rows and owned tombstones after a global USN cursor; call repeatedly until fewer than the requested limit are returned.';
comment on function public.list_orphaned_card_media(integer) is
  'Lists user-owned media references whose card is missing or soft-deleted; deletion from Storage belongs to a trusted cleanup worker.';
