import * as Sentry from "@sentry/deno";
const dsn = Deno.env.get("SENTRY_DSN");
const posthogToken = Deno.env.get("POSTHOG_PROJECT_TOKEN");
const posthogHost = Deno.env.get("POSTHOG_HOST") ?? "https://us.i.posthog.com";
Sentry.init({ dsn, enabled: Boolean(dsn), environment: Deno.env.get("SENTRY_ENVIRONMENT") ?? "production", tracesSampleRate: Number(Deno.env.get("SENTRY_TRACES_SAMPLE_RATE") ?? "0.1"), sendDefaultPii: false });
export function setRequestContext(c: {userId?: string; functionName: string; requestId: string}) { Sentry.setTag("edge_function", c.functionName); Sentry.setTag("request_id", c.requestId); if (c.userId) Sentry.setUser({id:c.userId}); }
export function captureException(error: unknown, c: {functionName: string; requestId: string; userId?: string; tags?: Record<string,string>; extra?: Record<string,unknown>}) { Sentry.withScope(scope => { scope.setTag("edge_function", c.functionName); scope.setTag("request_id", c.requestId); if(c.userId) scope.setUser({id:c.userId}); Object.entries(c.tags??{}).forEach(([k,v])=>scope.setTag(k,v)); Object.entries(c.extra??{}).forEach(([k,v])=>scope.setExtra(k,sanitize(v))); Sentry.captureException(error); }); }
export async function capturePostHogEvent(i: {distinctId:string; event:string; properties:Record<string,unknown>}) { if(!posthogToken || Deno.env.get("POSTHOG_SERVER_ENABLED")==="0") return; const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(),1500); try { await fetch(`${posthogHost.replace(/\/$/,"")}/i/v0/e/`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({api_key:posthogToken,event:i.event,distinct_id:i.distinctId,properties:{...sanitize(i.properties),$lib:"flashi-supabase-edge"}}),signal:controller.signal}); } catch(error) { console.warn(JSON.stringify({event:"posthog_delivery_failed",error:error instanceof Error?error.message:"unknown"})); } finally { clearTimeout(timeout); } }
function sanitize(v:unknown):unknown { if(v===null||v===undefined||typeof v!=="object") return v; if(Array.isArray(v)) return `[array:${v.length}]`; return Object.fromEntries(Object.entries(v as Record<string,unknown>).filter(([k])=>!/token|secret|password|authorization|cookie|prompt|response|front|back|content|email|goal|target_date|weekly_minutes|idempotency_key|fingerprint/i.test(k))); }
